### ISSUE TITLE
Fine-tuning for personal data

### ISSUE THREAD

**Issue by jundaz** [opendatalab/DocLayout-YOLO#19]
Hello there,
Thank you very much for sharing this model.
I have a dataset similar to D4LA and doclaynet and is wondering how to setup finetuning the pretrained model for my own data, do you mind sharing that?
Thanks again

**Comment by agombert** [comment]
Hey, 

Thanks for the great work. 

I just wonder if fine-tuning on personal data should be done with [this link](https://github.com/opendatalab/DocLayout-YOLO/blob/main/assets/script.sh#L17) by changing `--pretrain doclayout_yolo_docsynth300k_imgsz1600.pt` to any model (for instance `doclayout_yolo_docstructbench_imgsz1024.pt instead?). 

Can I also change to have 2 or 3 classes (different from the ones you've been using)? And if there is the case, do you have example I can take a look at to adapt my `yaml` file ?

```yaml
nc: 3

names:
  0: myfancyclass1
  1: myfancyclass2
  2: myfancyclass3

train: /path/to/images/train 
val: /path/to/images/val  
test: /path/to/images/test
```

And then all my images structures in `Yolo` format

For instance:
```txt
0 0.5 0.5 0.2 0.3
2 0.6 0.6 0.3 0.4
```

Or should I modify only the last layers of the net to add my own last layer for my own classification?

Best, 

Arnault
